default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['TOLUENE_DATABASE_USERNAME'] %>
  password: <%= ENV['TOLUENE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: Toluene_development
  username: <%= ENV['TOLUENE_DATABASE_USERNAME'] %>
  password: <%= ENV['TOLUENE_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: Toluene_test

production:
  <<: *default
  database: Toluene_production
  username: Toluene
  password: <%= ENV['TOLUENE_DATABASE_PASSWORD'] %>
